- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Ensure Apache2 is running
  service:
    name: apache2
    state: started
    enabled: true

- name: Create Apache test frontend site
  copy:
    dest: /var/www/html/index.html
    content: "<html><body><h1>Apache test site</h1></body></html>"
