- name: Install Python 3 and pip
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Install Django globally
  pip:
    name: django
    executable: pip3
