- name: Install PHP and dependencies
  apt:
    name:
      - php
      - php-cli
      - php-mbstring
      - php-xml
      - php-curl
      - php-mysql
      - php-zip
      - unzip
      - curl
      - composer
    state: present
    update_cache: yes 

- name: Install Laravel globally for appuser
  become: yes
  become_user: appuser
  shell: |
    export COMPOSER_HOME=$HOME/.config/composer
    export PATH="$COMPOSER_HOME/vendor/bin:$PATH"
    composer global require laravel/installer --no-interaction
  environment:
    COMPOSER_HOME: "/home/appuser/.config/composer"
    PATH: "/home/appuser/.config/composer/vendor/bin:/usr/local/bin:/usr/bin:/bin"
  args:
    executable: /bin/bash
    creates: /home/appuser/.config/composer/vendor/bin/laravel
